package edu.umg.ia.engine.domain;

public enum GameEvent {
	
	GAME_STARTED,

	INIT_CHAPTER_I,
	CHAPTER_I_GOAL_I_COMPLETED,
	CHAPTER_I_GOAL_II_COMPLETED,
	CHAPTER_I_GOAL_III_COMPLETED,
	
	INIT_CHAPTER_II,
	CHAPTER_II_GOAL_I_COMPLETED,
	CHAPTER_II_GOAL_II_COMPLETED,
	CHAPTER_II_GOAL_III_COMPLETED,

	INIT_CHAPTER_III,
	CHAPTER_III_GOAL_I_COMPLETED,
	CHAPTER_III_GOAL_II_COMPLETED,
	CHAPTER_III_GOAL_III_COMPLETED,
	
	EPILOGUE,
	END_GAME,
	NONE

	;
	
}
